/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MarketActivityService } from "../marketActivity.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MarketActivityCreateInput } from "./MarketActivityCreateInput";
import { MarketActivity } from "./MarketActivity";
import { MarketActivityFindManyArgs } from "./MarketActivityFindManyArgs";
import { MarketActivityWhereUniqueInput } from "./MarketActivityWhereUniqueInput";
import { MarketActivityUpdateInput } from "./MarketActivityUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MarketActivityControllerBase {
  constructor(
    protected readonly service: MarketActivityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MarketActivity })
  @nestAccessControl.UseRoles({
    resource: "MarketActivity",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMarketActivity(
    @common.Body() data: MarketActivityCreateInput
  ): Promise<MarketActivity> {
    return await this.service.createMarketActivity({
      data: data,
      select: {
        activityName: true,
        createdAt: true,
        evaluation: true,
        id: true,
        participants: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MarketActivity] })
  @ApiNestedQuery(MarketActivityFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MarketActivity",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async marketActivities(
    @common.Req() request: Request
  ): Promise<MarketActivity[]> {
    const args = plainToClass(MarketActivityFindManyArgs, request.query);
    return this.service.marketActivities({
      ...args,
      select: {
        activityName: true,
        createdAt: true,
        evaluation: true,
        id: true,
        participants: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MarketActivity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarketActivity",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async marketActivity(
    @common.Param() params: MarketActivityWhereUniqueInput
  ): Promise<MarketActivity | null> {
    const result = await this.service.marketActivity({
      where: params,
      select: {
        activityName: true,
        createdAt: true,
        evaluation: true,
        id: true,
        participants: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MarketActivity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarketActivity",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMarketActivity(
    @common.Param() params: MarketActivityWhereUniqueInput,
    @common.Body() data: MarketActivityUpdateInput
  ): Promise<MarketActivity | null> {
    try {
      return await this.service.updateMarketActivity({
        where: params,
        data: data,
        select: {
          activityName: true,
          createdAt: true,
          evaluation: true,
          id: true,
          participants: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MarketActivity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarketActivity",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMarketActivity(
    @common.Param() params: MarketActivityWhereUniqueInput
  ): Promise<MarketActivity | null> {
    try {
      return await this.service.deleteMarketActivity({
        where: params,
        select: {
          activityName: true,
          createdAt: true,
          evaluation: true,
          id: true,
          participants: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
