/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SalesProcessService } from "../salesProcess.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SalesProcessCreateInput } from "./SalesProcessCreateInput";
import { SalesProcess } from "./SalesProcess";
import { SalesProcessFindManyArgs } from "./SalesProcessFindManyArgs";
import { SalesProcessWhereUniqueInput } from "./SalesProcessWhereUniqueInput";
import { SalesProcessUpdateInput } from "./SalesProcessUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SalesProcessControllerBase {
  constructor(
    protected readonly service: SalesProcessService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SalesProcess })
  @nestAccessControl.UseRoles({
    resource: "SalesProcess",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSalesProcess(
    @common.Body() data: SalesProcessCreateInput
  ): Promise<SalesProcess> {
    return await this.service.createSalesProcess({
      data: data,
      select: {
        createdAt: true,
        customer: true,
        followUp: true,
        id: true,
        salesStage: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SalesProcess] })
  @ApiNestedQuery(SalesProcessFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SalesProcess",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salesProcesses(
    @common.Req() request: Request
  ): Promise<SalesProcess[]> {
    const args = plainToClass(SalesProcessFindManyArgs, request.query);
    return this.service.salesProcesses({
      ...args,
      select: {
        createdAt: true,
        customer: true,
        followUp: true,
        id: true,
        salesStage: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SalesProcess })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SalesProcess",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salesProcess(
    @common.Param() params: SalesProcessWhereUniqueInput
  ): Promise<SalesProcess | null> {
    const result = await this.service.salesProcess({
      where: params,
      select: {
        createdAt: true,
        customer: true,
        followUp: true,
        id: true,
        salesStage: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SalesProcess })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SalesProcess",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSalesProcess(
    @common.Param() params: SalesProcessWhereUniqueInput,
    @common.Body() data: SalesProcessUpdateInput
  ): Promise<SalesProcess | null> {
    try {
      return await this.service.updateSalesProcess({
        where: params,
        data: data,
        select: {
          createdAt: true,
          customer: true,
          followUp: true,
          id: true,
          salesStage: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SalesProcess })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SalesProcess",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSalesProcess(
    @common.Param() params: SalesProcessWhereUniqueInput
  ): Promise<SalesProcess | null> {
    try {
      return await this.service.deleteSalesProcess({
        where: params,
        select: {
          createdAt: true,
          customer: true,
          followUp: true,
          id: true,
          salesStage: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
