/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { EmailCampaign } from "./EmailCampaign";
import { EmailCampaignCountArgs } from "./EmailCampaignCountArgs";
import { EmailCampaignFindManyArgs } from "./EmailCampaignFindManyArgs";
import { EmailCampaignFindUniqueArgs } from "./EmailCampaignFindUniqueArgs";
import { CreateEmailCampaignArgs } from "./CreateEmailCampaignArgs";
import { UpdateEmailCampaignArgs } from "./UpdateEmailCampaignArgs";
import { DeleteEmailCampaignArgs } from "./DeleteEmailCampaignArgs";
import { EmailCampaignService } from "../emailCampaign.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EmailCampaign)
export class EmailCampaignResolverBase {
  constructor(
    protected readonly service: EmailCampaignService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EmailCampaign",
    action: "read",
    possession: "any",
  })
  async _emailCampaignsMeta(
    @graphql.Args() args: EmailCampaignCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EmailCampaign])
  @nestAccessControl.UseRoles({
    resource: "EmailCampaign",
    action: "read",
    possession: "any",
  })
  async emailCampaigns(
    @graphql.Args() args: EmailCampaignFindManyArgs
  ): Promise<EmailCampaign[]> {
    return this.service.emailCampaigns(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EmailCampaign, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EmailCampaign",
    action: "read",
    possession: "own",
  })
  async emailCampaign(
    @graphql.Args() args: EmailCampaignFindUniqueArgs
  ): Promise<EmailCampaign | null> {
    const result = await this.service.emailCampaign(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EmailCampaign)
  @nestAccessControl.UseRoles({
    resource: "EmailCampaign",
    action: "create",
    possession: "any",
  })
  async createEmailCampaign(
    @graphql.Args() args: CreateEmailCampaignArgs
  ): Promise<EmailCampaign> {
    return await this.service.createEmailCampaign({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EmailCampaign)
  @nestAccessControl.UseRoles({
    resource: "EmailCampaign",
    action: "update",
    possession: "any",
  })
  async updateEmailCampaign(
    @graphql.Args() args: UpdateEmailCampaignArgs
  ): Promise<EmailCampaign | null> {
    try {
      return await this.service.updateEmailCampaign({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EmailCampaign)
  @nestAccessControl.UseRoles({
    resource: "EmailCampaign",
    action: "delete",
    possession: "any",
  })
  async deleteEmailCampaign(
    @graphql.Args() args: DeleteEmailCampaignArgs
  ): Promise<EmailCampaign | null> {
    try {
      return await this.service.deleteEmailCampaign(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
