/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CustomerInfoService } from "../customerInfo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CustomerInfoCreateInput } from "./CustomerInfoCreateInput";
import { CustomerInfo } from "./CustomerInfo";
import { CustomerInfoFindManyArgs } from "./CustomerInfoFindManyArgs";
import { CustomerInfoWhereUniqueInput } from "./CustomerInfoWhereUniqueInput";
import { CustomerInfoUpdateInput } from "./CustomerInfoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CustomerInfoControllerBase {
  constructor(
    protected readonly service: CustomerInfoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CustomerInfo })
  @nestAccessControl.UseRoles({
    resource: "CustomerInfo",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCustomerInfo(
    @common.Body() data: CustomerInfoCreateInput
  ): Promise<CustomerInfo> {
    return await this.service.createCustomerInfo({
      data: {
        ...data,

        customerLevel: data.customerLevel
          ? {
              connect: data.customerLevel,
            }
          : undefined,
      },
      select: {
        address: true,
        communicationContent: true,
        companyInfo: true,
        contactInfo: true,
        createdAt: true,

        customerLevel: {
          select: {
            id: true,
          },
        },

        followUpLogs: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CustomerInfo] })
  @ApiNestedQuery(CustomerInfoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerInfo",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerInfos(@common.Req() request: Request): Promise<CustomerInfo[]> {
    const args = plainToClass(CustomerInfoFindManyArgs, request.query);
    return this.service.customerInfos({
      ...args,
      select: {
        address: true,
        communicationContent: true,
        companyInfo: true,
        contactInfo: true,
        createdAt: true,

        customerLevel: {
          select: {
            id: true,
          },
        },

        followUpLogs: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CustomerInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerInfo",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerInfo(
    @common.Param() params: CustomerInfoWhereUniqueInput
  ): Promise<CustomerInfo | null> {
    const result = await this.service.customerInfo({
      where: params,
      select: {
        address: true,
        communicationContent: true,
        companyInfo: true,
        contactInfo: true,
        createdAt: true,

        customerLevel: {
          select: {
            id: true,
          },
        },

        followUpLogs: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CustomerInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerInfo",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCustomerInfo(
    @common.Param() params: CustomerInfoWhereUniqueInput,
    @common.Body() data: CustomerInfoUpdateInput
  ): Promise<CustomerInfo | null> {
    try {
      return await this.service.updateCustomerInfo({
        where: params,
        data: {
          ...data,

          customerLevel: data.customerLevel
            ? {
                connect: data.customerLevel,
              }
            : undefined,
        },
        select: {
          address: true,
          communicationContent: true,
          companyInfo: true,
          contactInfo: true,
          createdAt: true,

          customerLevel: {
            select: {
              id: true,
            },
          },

          followUpLogs: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CustomerInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerInfo",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCustomerInfo(
    @common.Param() params: CustomerInfoWhereUniqueInput
  ): Promise<CustomerInfo | null> {
    try {
      return await this.service.deleteCustomerInfo({
        where: params,
        select: {
          address: true,
          communicationContent: true,
          companyInfo: true,
          contactInfo: true,
          createdAt: true,

          customerLevel: {
            select: {
              id: true,
            },
          },

          followUpLogs: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
