/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Quotation } from "./Quotation";
import { QuotationCountArgs } from "./QuotationCountArgs";
import { QuotationFindManyArgs } from "./QuotationFindManyArgs";
import { QuotationFindUniqueArgs } from "./QuotationFindUniqueArgs";
import { CreateQuotationArgs } from "./CreateQuotationArgs";
import { UpdateQuotationArgs } from "./UpdateQuotationArgs";
import { DeleteQuotationArgs } from "./DeleteQuotationArgs";
import { QuotationService } from "../quotation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Quotation)
export class QuotationResolverBase {
  constructor(
    protected readonly service: QuotationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Quotation",
    action: "read",
    possession: "any",
  })
  async _quotationsMeta(
    @graphql.Args() args: QuotationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Quotation])
  @nestAccessControl.UseRoles({
    resource: "Quotation",
    action: "read",
    possession: "any",
  })
  async quotations(
    @graphql.Args() args: QuotationFindManyArgs
  ): Promise<Quotation[]> {
    return this.service.quotations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Quotation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Quotation",
    action: "read",
    possession: "own",
  })
  async quotation(
    @graphql.Args() args: QuotationFindUniqueArgs
  ): Promise<Quotation | null> {
    const result = await this.service.quotation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Quotation)
  @nestAccessControl.UseRoles({
    resource: "Quotation",
    action: "create",
    possession: "any",
  })
  async createQuotation(
    @graphql.Args() args: CreateQuotationArgs
  ): Promise<Quotation> {
    return await this.service.createQuotation({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Quotation)
  @nestAccessControl.UseRoles({
    resource: "Quotation",
    action: "update",
    possession: "any",
  })
  async updateQuotation(
    @graphql.Args() args: UpdateQuotationArgs
  ): Promise<Quotation | null> {
    try {
      return await this.service.updateQuotation({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Quotation)
  @nestAccessControl.UseRoles({
    resource: "Quotation",
    action: "delete",
    possession: "any",
  })
  async deleteQuotation(
    @graphql.Args() args: DeleteQuotationArgs
  ): Promise<Quotation | null> {
    try {
      return await this.service.deleteQuotation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
